run:
  concurrency: 4
  timeout: 5m

linters:
  disable-all: true
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - contextcheck
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goerr113
    - gofmt
##    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - maintidx
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
  gocognit:
    min-complexity: 10
  nestif:
    min-complexity: 4
  unparam:
    check-exported: true
